name: GitHub Actions Hello World
run-name: ${{ github.actor }} is starting GitHub Actions
on: [push]
jobs:
  Explore-GitHub-Actions:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: configure
        run: make say-hello
